name: Opsless - System

on:
  push:
    branches:
      - master
    paths:
      - 'opsless_system/**/*.tf'  # Only trigger if files in opsless_system/ are changed
      - '.github/workflows/opsless_system.yml'  # (optional) if you want updates to the workflow itself to trigger a run

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        working-directory: opsless_system
        run: terraform init

      - name: Terraform Plan
        working-directory: opsless_system
        run: terraform plan -input=false -var="bucket_name=opsless-tfstate"

      - name: Terraform Apply
        working-directory: opsless_system
        run: terraform apply -auto-approve -input=false -var="bucket_name=opsless-tfstate"
